config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :inquiries do
    resources :answers, only: [:create]
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :inquiry
  belongs_to :user
  validates :inquiry_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user
  has_many :answers
  validates :user_id, presence: true
  validates :subject, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }

  def posted_by?(logined_user)
    logined_user == user
  end
end

app/models/inquiry_save_and_slack_decorator.rb
class InquirySaveAndSlackDecorator
  include ActiveModel::Model
  WEB_SLACK = ENV["WEB_SLACK"]
  define_model_callbacks :save, only: :after
  after_save :post_slack
  attr_reader :inquiry

  def initialize(inquiry)
    @inquiry = inquiry
  end

  def save
    run_callbacks :save do
      inquiry.save
    end
  end

  private

    def post_slack
      slack.post text: "質問 #{inquiry.subject}"
    end
  
    def slack
      notifier = Slack::Notifier.new(
        WEB_SLACK,
        username: "通知" )
    end
end

app/models/make_inquiry_post_slack.rb
class MakeInquiryPostSlack
  include ActiveModel::Model
  define_model_callbacks :save, only: :after
  after_save :post_slack
  attr_reader :inquiry

  def initialize(inquiry)
    @inquiry = inquiry
  end

  def save
    run_callbacks :save do
      @inquiry.save
    end
  end

  private

    def post_slack
      slack.post text: "質問 #{@inquiry.subject}"
    end
  
    def slack
      notifier = Slack::Notifier.new(
        "https://hooks.slack.com/services/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",
        username: "通知"
      )
    end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_many :inquiries
  has_many :answers
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { in: 9..200 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :require_login, only: [:create]

  def create
    inquiry = Inquiry.find(params[:inquiry_id])
    @answer = inquiry.answers.create(answer_params.merge(user_id: current_user.id))
    redirect_to inquiry
  end

  private
    def answer_params
      params.require(:answer).permit(:content)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def require_login
      unless logged_in?
        flash[:danger] = "ログインが必要です"
        redirect_to login_url
      end
    end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update]
  before_action :require_login, only: [:new, :edit, :create, :update]
  before_action :edit_permition_require, only: [:edit, :update]

  def index
    @inquiries = Inquiry.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @answers = @inquiry.answers.order(created_at: :desc)
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  def edit
  end

  # POST /inquiries
  def create
    @inquiry_post_slack = InquirySaveAndSlackDecorator.new(current_user.inquiries.build(inquiry_params))

    if @inquiry_post_slack.save
      redirect_to @inquiry_post_slack.inquiry
    else
      render :new
    end
  end

  def update
    if @inquiry.update(inquiry_params)
      redirect_to @inquiry
    else
      render :edit
    end
  end

  private

    def inquiry_params
      params.require(:inquiry).permit(:subject, :body)
    end

    def edit_permition_require
      redirect_to @inquiry unless @inquiry.posted_by?(current_user)
    end

    def set_inquiry
      @inquiry ||= Inquiry.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスかパスワードが間違っています'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end

  private

    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    current_user.present?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inquiries/_form.html.haml
= form_with model: @inquiry, local: true do |f|
  - if @inquiry.errors.any?
    #error_explanation
      %h2= "入力エラー"
      %ul
        - @inquiry.errors.full_messages.each do |message|
          %li= message

  .form.form-group
    = f.label :subject
    = f.text_field :subject, class: "form-control"
  .form.form-group
    = f.label :body
    = f.text_area :body, rows: 20, class: "form-control"
  .actions
    = f.submit '質問を投稿する'

app/views/inquiries/edit.html.haml
.container
  %h1 質問を編集

  = form_with model: @inquiry, local: true do |f|
    - if @inquiry.errors.any?
      #error_explanation
        %h2 入力エラー
        %ul
          - @inquiry.errors.full_messages.each do |message|
            %li= message

    .form.form-group
      = f.label :subject
      = f.text_field :subject, class: "form-control"
    .form.form-group
      = f.label :body
      = f.text_area :body, rows: 20, class: "form-control"
    .actions
      = f.submit '編集'

  = link_to '戻る', @inquiry

app/views/inquiries/index.html.haml
.container
  %h1 質問一覧

  %table.table
    %thead
      %tr
        %th 投稿者
        %th id
        %th 質問
    %tbody
      - @inquiries.each do |inquiry|
        %tr
          %td= inquiry.user.name
          %td= inquiry.id
          %td= link_to inquiry.subject, inquiry
  = paginate @inquiries

app/views/inquiries/new.html.haml
.container
  %h1 質問画面

  = render 'form'

  = link_to '戻る', inquiries_path

app/views/inquiries/show.html.haml
.container
  %h2= @inquiry.subject

  .container.well
    = simple_format(@inquiry.body)
  = link_to "一覧を表示する", inquiries_path
  - if @inquiry.posted_by?(current_user)
    = link_to "編集する", edit_inquiry_path

  .container
    - @answers.each do |answer|
      .panel.panel-primary
        .panel-heading= answer.user.name
        .panel-body.answer-content= simple_format(answer.content)
    - if logged_in?
      = form_with model: Answer.new, local: true, url: inquiry_answers_path(@inquiry) do |f|
        .form.form-group
          = f.label :content
          = f.text_area :content, rows: 10, class: "form-control"
        = f.hidden_field :inquiry, :value => @inquiry.id
        .actions
          = f.submit '回答する'

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-inverse.navbar-static-top
    .container-fluid
      .navbar-header
        %a.navbar-brand 質問アプリ
        %a.navbar-brand
          = link_to "質問を投稿", new_inquiry_path, class: "navbar-brand"
      .collapse.navbar-collapse.navbar-right
        -if logged_in?
          .navbar-text
            = current_user.name
        %ul.nav.navbar-nav
          - if logged_in?
            %li
              = link_to "ログアウト", logout_path, method: :delete
          - else
            %li
              = link_to "ログイン", login_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Pilotprojectwiki
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    - flash.each do |key,value|
      = content_tag(:div, value, class: "#{key}")
    = yield

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{@user.errors.count} つのエラー"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .form.form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form.form-group
    = f.label :email
    = f.email_field :email, class: "form-control"
  .form.form-group
    = f.label :password
    = f.password_field :password, class: "form-control"
  .form.form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: "form-control"
  .actions
    = f.submit '新規作成'

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Email
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
.container
  %h1.big ユーザー登録

  = render 'form'

  = link_to '戻る', users_path